version: '3.8'

services:
  mysql:
    image: mysql:latest  # Imagem oficial do MySQL
    environment:
      MYSQL_DATABASE: barbeshopdb  # Nome do banco de dados
      MYSQL_ROOT_PASSWORD: admin  # Senha do root do MySQL
    ports:
      - "3306:3306"  # Mapeia a porta 3306 do container para a porta 3306 do host
  baber-shop-api:
    build: .  # Constrói a imagem a partir do Dockerfile no diretório atual
    ports:
      - "8080:8080"  # Mapeia a porta 8080 do container para a porta 8080 do host
    depends_on:
      - mysql  # Espera o MySQL iniciar antes de iniciar o aplicativo